/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacePackage;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
//import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Bib3k
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    
    public Admin() {
        initComponents();
        ComboBoxLoad();
        //ProfessorApprovalCB(name, tableName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton9 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        StudentAPCB = new javax.swing.JComboBox<>();
        ProfessorAPCB = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        StudentApproveBtn = new javax.swing.JButton();
        StudentReviewBtn = new javax.swing.JButton();
        StudentRejectBtn = new javax.swing.JButton();
        ProfRejectBtn = new javax.swing.JButton();
        ProfReviewBtn = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ProfessorAPCB1 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        ProfReviewBtn1 = new javax.swing.JButton();
        ProfRejectBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Panel");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(204, 244, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel4.setLayout(new java.awt.CardLayout());

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setBackground(new java.awt.Color(204, 198, 200));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("User ID");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Password");

        jPasswordField1.setText("jPasswordField1");

        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton9.setText("Login");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 190, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel8, "card2");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Student Approval List");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Forgot Password");

        StudentAPCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentAPCBMouseClicked(evt);
            }
        });
        StudentAPCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentAPCBActionPerformed(evt);
            }
        });

        ProfessorAPCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfessorAPCBMouseClicked(evt);
            }
        });
        ProfessorAPCB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ProfessorAPCBKeyPressed(evt);
            }
        });

        jButton10.setText("Approve");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        StudentApproveBtn.setText("Approve");
        StudentApproveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentApproveBtnMouseClicked(evt);
            }
        });
        StudentApproveBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StudentApproveBtnKeyPressed(evt);
            }
        });

        StudentReviewBtn.setText("Review");
        StudentReviewBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentReviewBtnMouseClicked(evt);
            }
        });

        StudentRejectBtn.setText("Reject");
        StudentRejectBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentRejectBtnMouseClicked(evt);
            }
        });
        StudentRejectBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StudentRejectBtnKeyPressed(evt);
            }
        });

        ProfRejectBtn.setText("Reject");
        ProfRejectBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfRejectBtnMouseClicked(evt);
            }
        });

        ProfReviewBtn.setText("Review");
        ProfReviewBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfReviewBtnMouseClicked(evt);
            }
        });

        jButton16.setText("Log Out");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton16MouseExited(evt);
            }
        });
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Professsor Approval List");

        ProfessorAPCB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfessorAPCB1MouseClicked(evt);
            }
        });
        ProfessorAPCB1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ProfessorAPCB1KeyPressed(evt);
            }
        });

        jButton11.setText("Approve");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        ProfReviewBtn1.setText("Review");
        ProfReviewBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfReviewBtn1MouseClicked(evt);
            }
        });

        ProfRejectBtn1.setText("Reject");
        ProfRejectBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfRejectBtn1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addComponent(jButton16)
                .addGap(76, 76, 76))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addComponent(StudentAPCB, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(StudentApproveBtn))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(ProfessorAPCB, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ProfessorAPCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(63, 63, 63)))
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton11)
                                    .addComponent(jButton10))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(ProfReviewBtn)
                                .addGap(18, 18, 18)
                                .addComponent(ProfRejectBtn))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(StudentReviewBtn)
                                .addGap(18, 18, 18)
                                .addComponent(StudentRejectBtn))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(ProfReviewBtn1)
                                .addGap(18, 18, 18)
                                .addComponent(ProfRejectBtn1))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton16)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentAPCB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentApproveBtn)
                    .addComponent(StudentReviewBtn)
                    .addComponent(StudentRejectBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfessorAPCB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10)
                    .addComponent(ProfReviewBtn)
                    .addComponent(ProfRejectBtn))
                .addGap(45, 45, 45)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProfessorAPCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton11)
                        .addComponent(ProfReviewBtn1)
                        .addComponent(ProfRejectBtn1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel9, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void StudentApprovalCB()
    {
        //jComboBox3.removeAll();
        
        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trialcollege","root", "NewPassword");
             String query = "select stud_name from studenttemptable";
             
             PreparedStatement ps = con.prepareStatement(query);
             ResultSet rs = ps.executeQuery();
             
             
             while(rs.next())
             {
                 StudentAPCB.addItem(rs.getString("stud_name"));
                 System.out.println(rs.getString("stud_name"));
             }
            
        }
        catch(Exception e)
        {
            System.out.println("Admin Panel2 ComboBOx Issue : "+e);            
        }
    }

    public void ProfessorApprovalCB()
    {
        
        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trialcollege","root", "NewPassword");
             String query = "select prof_name from professortemptable";

             PreparedStatement ps = con.prepareStatement(query);
             
             ResultSet rs = ps.executeQuery();
             
             while(rs.next())
             {
                 ProfessorAPCB.addItem(rs.getString("prof_name"));
                 System.out.println(rs.getString("prof_name"));
                 
             }
            
        }
        catch(Exception e)
        {
            System.out.println("Admin Panel2 ComboBOx Issue : "+e);            
        }
    }


    private void StudentAPCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentAPCBActionPerformed
       
        /* Once this drop down menu is clicked I am going to connect
        to the database and update the list in the drop down menu*/
        
        
    }//GEN-LAST:event_StudentAPCBActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        this.dispose();
        LoginForm obj = new LoginForm();
        obj.setVisible(true);
        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        //Logging in 
        try{
            LoginForm obj = new LoginForm();
            String userid = jTextField1.getText();
            //char[] tempPassword = jPasswordField1.getPassword();
            String tempPassword = Arrays.toString(jPasswordField1.getPassword());
            System.out.println(tempPassword+" "+userid);
            
            //Debugging
            
            boolean login = obj.AuthenticatorForProfessor(userid, tempPassword);
            System.out.println(login);
            if(login)
            {
                jPanel4.removeAll();
                jPanel4.repaint();
                jPanel4.revalidate();
                
                
                jPanel4.add(jPanel9);
                jPanel4.repaint();
                jPanel4.revalidate();
                
            }
            
            else
            {
                jLabel8.setText("Login Failed");
                
            }
            
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void StudentAPCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentAPCBMouseClicked
    ComboBoxLoad();
    jLabel2.setText("");
       
    }//GEN-LAST:event_StudentAPCBMouseClicked

    private void ProfessorAPCBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProfessorAPCBKeyPressed
        //ProfessorAPCB.removeAllItems();
        //System.out.println("AM I running");
        //this.ProfessorApprovalCB();
    }//GEN-LAST:event_ProfessorAPCBKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        
    }//GEN-LAST:event_jButton1KeyPressed

    private void StudentApproveBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StudentApproveBtnKeyPressed
        
    }//GEN-LAST:event_StudentApproveBtnKeyPressed

    private void StudentApproveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentApproveBtnMouseClicked
        String a = StudentAPCB.getItemAt(StudentAPCB.getSelectedIndex());
        System.out.println(a);
        
        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trialcollege","root", "NewPassword");
             String query = "insert into student select * from studenttemptable where stud_name = ?";
             PreparedStatement ps = con.prepareStatement(query);
             ps.setString(1, a);
             ps.execute();
             JOptionPane.showMessageDialog(this,"Approved");
             DeleteFromSql(a);
        }
        catch(Exception e)
        {
            System.out.println(e);
                      
        }
        
        
        
        
    }//GEN-LAST:event_StudentApproveBtnMouseClicked

    private void StudentReviewBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentReviewBtnMouseClicked
        String a = StudentAPCB.getItemAt(StudentAPCB.getSelectedIndex());
        System.out.println("Hehlloo"+a);
        String dialog = "";
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trialcollege","root","NewPassword");
            PreparedStatement stm = con.prepareStatement("select * from studenttemptable where stud_name = ?");
            stm.setString(1, a);
            ResultSet rs = stm.executeQuery();
            while(rs.next())
            {
                a = "Name = "+rs.getString(1)+"\nStud_roll = "+rs.getInt(2)+"\nStud_course = "+rs.getInt(3)+"\nStud_sem = "+rs.getInt(4);
                System.out.println(a);
            }
            JOptionPane.showMessageDialog(this,a);
            
        }
        catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_StudentReviewBtnMouseClicked

    private void StudentRejectBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StudentRejectBtnKeyPressed
        
    }//GEN-LAST:event_StudentRejectBtnKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        ComboBoxLoad();
        jLabel2.setText("");
        jLabel3.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    
    public void DeleteFromSql(String a)
    {
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trialcollege","root","NewPassword");
            PreparedStatement stm = con.prepareStatement("delete from studenttemptable where stud_name = ?");
            
            stm.setString(1, a);
            
            stm.executeUpdate();
        }
        catch(Exception e){System.out.println(e);}    
    }
    
    public void DeleteFromProftt(String a)
    {
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trialcollege","root","NewPassword");
            PreparedStatement stm = con.prepareStatement("delete from professortemptable where prof_name = ?");
            stm.setString(1, a);
            stm.executeUpdate();
        }
        catch(Exception e){System.out.println(e);}
        
    }
    
    private void StudentRejectBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentRejectBtnMouseClicked
        String a = StudentAPCB.getItemAt(StudentAPCB.getSelectedIndex());
        System.out.println("Helloo"+a);
        DeleteFromSql(a);
        jLabel2.setText("Record Deleted");
        
    }//GEN-LAST:event_StudentRejectBtnMouseClicked

    private void ProfRejectBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfRejectBtnMouseClicked
        String a = ProfessorAPCB.getItemAt(ProfessorAPCB.getSelectedIndex());
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trialcollege","root","NewPassword");
            PreparedStatement stm = con.prepareStatement("delete from professortemptable where prof_name = ?");
            
            stm.setString(1, a);
            
            stm.executeUpdate();
            
            jLabel3.setText("Record Deleted");
            
            
        }
        catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_ProfRejectBtnMouseClicked

    private void ProfessorAPCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfessorAPCBMouseClicked
        ComboBoxLoad();
        jLabel3.setText("");
    }//GEN-LAST:event_ProfessorAPCBMouseClicked

    private void ProfReviewBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfReviewBtnMouseClicked
        String a = ProfessorAPCB.getItemAt(ProfessorAPCB.getSelectedIndex());
        System.out.println("Helloo"+a);
        String dialog = "";
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trialcollege","root","NewPassword");
            PreparedStatement stm = con.prepareStatement("select * from professortemptable where prof_name = ?");
            stm.setString(1, a);
            ResultSet rs = stm.executeQuery();
            while(rs.next())
            {
                a = "Prof Name = "+rs.getString(2)+"\nProf roll = "+rs.getInt(1)+"\nProf Sub = "+rs.getInt(3)+"\nProf sem = "+rs.getInt(4);
                System.out.println(a);
            }
            JOptionPane.showMessageDialog(this,a);
            
        }
        catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_ProfReviewBtnMouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
    String a = ProfessorAPCB.getItemAt(ProfessorAPCB.getSelectedIndex());
        System.out.println(a);
        
        try{

            Class.forName("com.mysql.cj.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/trialcollege","root", "NewPassword");
             String query = "insert into professor select * from professortemptable where prof_name = ?";
             PreparedStatement ps = con.prepareStatement(query);
             ps.setString(1, a);
             ps.execute();
             JOptionPane.showMessageDialog(this,"Approved");
             DeleteFromProftt(a);
        }
        catch(Exception e)
        {
            System.out.println(e);
                      
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
        jButton9.setBackground(Color.green);
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
        jButton9.setBackground(Color.white);
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseEntered
        jButton16.setBackground(Color.red);
    }//GEN-LAST:event_jButton16MouseEntered

    private void jButton16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseExited
        jButton16.setBackground(Color.white);
    }//GEN-LAST:event_jButton16MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(Color.green);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(Color.white);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        
    }//GEN-LAST:event_jButton9MouseClicked

    private void ProfessorAPCB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfessorAPCB1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfessorAPCB1MouseClicked

    private void ProfessorAPCB1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProfessorAPCB1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfessorAPCB1KeyPressed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11MouseClicked

    private void ProfReviewBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfReviewBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfReviewBtn1MouseClicked

    private void ProfRejectBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfRejectBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfRejectBtn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }
    
    public void ComboBoxLoad()
    {
        StudentAPCB.removeAllItems();
        this.StudentApprovalCB();
        ProfessorAPCB.removeAllItems();
        this.ProfessorApprovalCB();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ProfRejectBtn;
    private javax.swing.JButton ProfRejectBtn1;
    private javax.swing.JButton ProfReviewBtn;
    private javax.swing.JButton ProfReviewBtn1;
    private javax.swing.JComboBox<String> ProfessorAPCB;
    private javax.swing.JComboBox<String> ProfessorAPCB1;
    private javax.swing.JComboBox<String> StudentAPCB;
    private javax.swing.JButton StudentApproveBtn;
    private javax.swing.JButton StudentRejectBtn;
    private javax.swing.JButton StudentReviewBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
